apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: w1suhac5w-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/w1suhac5w-java-springboot-gitops